### PR TITLE
Changed preferences import method: from module to Jitpack library

### PR DESCRIPTION
**Pull request by CremaLuca**
- Moved `preferences` from being a module to being a dependency imported via jitpack
- Updated `smslibrary` in order to have InvalidTelephoneNumberException
- Moved `RingtoneHandler` in `structure` package (as intended by group 4 project)

These changes should be the same as those requested by @giovannivelludo, so those pull requests could be marked as duplicate if we can approve this one.

Now the project compiles and can be built correctly.

One day we could pass `smslibrary` from submodule to Jitpack library, it's less of a pain in the a**.

### CODE REVIEW

**Review by Cogno-Marco — COMMENTED** [review]
File changes seem all good, my main concern is, how does jitpack work? Can I have more info?

**Comment by CremaLuca** [comment]
I'm not much of a good explainer so see for yourself
https://jitpack.io/
This service acts like a source for libraries where gradle can look for, and the libraries are made of git repositories

**Comment by tonin-alessandra** [comment]
I'm not sure I understood correctly what JitPack does: we want to set 'preferences' as a dependency of the project, right?
So we use this tool that does all by itself and then we simply have to import the created package?

**Comment by CremaLuca** [comment]
Its purpose is to be a source for gradle dependencies by taking public repositories, compiling them (with tests and everything) and then let them be available to be used inside an Android project.

**Comment by tonin-alessandra** [comment]
Thank you very much, I learnt something new.
I really like this idea.

**Review by tonin-alessandra — APPROVED** [review]

**Review by albertoursino — APPROVED** [review]
Everything correct as far as I can see.
I like the _jitPack_ method.
In the aae0877 commit of the pull request related to the AppManager class: https://github.com/Cogno-IDU/killer-app/pull/12 I also move the RingtoneHandler class from the package **RingCommands** to **structure**, I hope no conflicts will be generated.

Alberto

**Comment by Cogno-Marco** [comment]
@AlbertoUrsino thanks for letting us know! We'll see when these get merged. It's not a hard fix anyway, just Alt+Enter in the worst case scenario 😉

**Review by Cogno-Marco — APPROVED** [review]
Crema told me how jitpack works, it seems like a really good solution, so I'd like to try this to see if it works.

**Pull request merged**
