### PR TITLE
updated submodule library, to include changes to its .gitignore

### PR DESCRIPTION
**Pull request by giovannivelludo**
I'm sorry for the multiple commits that add nothing, but that's what GitHub did when merging branch master from Cogno-IDU into EIS0's master, after having merged EIS0's hotfix/gitignore into EIS0's master branch.

### CODE REVIEW

**Comment by Cogno-Marco** [comment]
This is not my fault, it's how submodules work. They don't update automatically, they need to be manually updated.
Also since the smslibrary is not yet complete, I don't think it's time yet to update the submodule, I would wait for something more from the smslibrary central repo before updating submodules both here and in network-dictionary

**Comment by giovannivelludo** [comment]
I need the submodule to be updated in order to be able to review pull requests to this repo in Android Studio, otherwise the fucked .gitignore will cause Android Studio to throw all kinds of errors when opening the project and switching branches.

**Comment by Cogno-Marco** [comment]
Nope, pull request reviews can (and should) be made to github.com

**Comment by giovannivelludo** [comment]
That's what I did! Where else would I open pull requests?

**Comment by Cogno-Marco** [comment]
> I need the submodule to be updated in order to be able to review pull requests to this repo in Android Studio

I'm talking about this. Both looking at pull requests and doing code review can (and should) be done directly in github.com by going into the Changes tab, where you can look at the code edited and comment specific lines. Why do you need Android Studio if you can just use github's proper tools?

**Comment by giovannivelludo** [comment]
I need Android Studio to check out the branch of the person making the pull request to see if the app builds, if he ignored important warnings, to test it, and in general to get a better understanding of the project (for example, if the person deleted some classes or methods and moved their functionalities to other classes, I can spot that quicker and can avoid asking why those deletions were made)

**Comment by Cogno-Marco** [comment]
That's not what the code review is about. We had an entire lesson on this. It's just checking what was written to improve it. If stuff get's moved, deleted, changed or added you can directly see it.
What you're trying to do (testing to see if it's still working) it's something that gets usually automated using Continuous Integrations (CI) and that we can automate using Github's Actions.
Even if stuff gets broken by a pull-request, eventually someone will find out since we're about 20 people working on the same stuff.

**Comment by giovannivelludo** [comment]
We're not yet using CI tools, and I can't see Android Studio warnings on GitHub

**Comment by Cogno-Marco** [comment]
What it's bothering me is that you're basically trying to get code from pull-request to check if it's working. What's stopping you then from updating code from everyone? And what if it's you changing something that breaks everything? Will you get the blame?

And if you're not getting from pull requests, then you're getting it from the central repo. Then why don't you just get it into the fork and work from there? So you don't need to push and force changes to everyone. So that you can work by yourself and do what you need to do.
I remember you that you can push/pull/merge however you want inside the fork.

**Comment by giovannivelludo** [comment]
> What it's bothering me is that you're basically trying to get code from pull-request to check if it's working.

Why does what I do on my PC bother you?

>What's stopping you then from updating code from everyone?

What do you mean with "updating code from everyone"? I just want to be able to check out the person's branch to see if everything works

>And what if it's you changing something that breaks everything? Will you get the blame?

I won't make any changes to their code (as I don't have permissions to push to other people's branches, outside of group 0's repositories), I just want to be able to check out their branch on my PC. If everybody has the old version of smslibrary in their branch, then I won't be able to do it without getting errors from Android Studio.

>And if you're not getting from pull requests, then you're getting it from the central repo.

Getting what?

You didn't address my points on CI tools and Android Studio warnings.

**Comment by CremaLuca** [comment]
I don't see a particular reason to update smslibrary at this point of development, but I can't see a reason why not either.

**Comment by Cogno-Marco** [comment]
Alright, I'll merge this to let you work I guess, we don't get much anyway from this pull request, it just seems... like there's something off...

**Comment by giovannivelludo** [comment]
Just checking in to point out an example of why code in pull requests should also be viewed in Android Studio: had the 3 reviewers done this for pull request #3, they would have gotten my same VCS root mapping error in Android Studio (#11), and they probably would have requested changes to vcs.xml before merging it.

**Pull request merged**
