### PR TITLE
fixed dependencies in app's build.gradle

### PR DESCRIPTION
**Pull request by giovannivelludo**
Changes are the same as #11 (if that pull request is accepted then you'll only see new changes), plus I added a dependency on module `smslibrary` in module `app` to make imports from that module work, and fixed package `preferences`' name in a class that was importing that package

### CODE REVIEW

**Comment by Cogno-Marco** [comment]
Damn it, you don't have to open a pull request every time you want to add edits to a pull request you already opened. As you even said this is basically all the changes in #11 + other changes. Next time pls, either add edits to a pull request you already opened or open a new pull request with only the stuff you're adding.

**Comment by giovannivelludo** [comment]
It wasn't possible to open a new pull request with only the last commit. What I first did was adding the changes to #11, but then I figured it would be sketchy to add stuff after you had already approved it.

**Comment by Cogno-Marco** [comment]
as long as it's not merged you can add stuff to it how/when you want (in my opinion at least)

**Comment by Cogno-Marco** [comment]
Labeling this as duplicate due to this comment in #16 
> These changes should be the same as those requested by @giovannivelludo, so those pull requests could be marked as duplicate if we can approve this one.

**Pull request closed without merging**
